#!/bin/sh
# Elliot one-command installer.
#
#   curl -LsSf https://raw.githubusercontent.com/EliBarak12/Elliot/main/scripts/install.sh | sh
#
# Pulls the pre-built Elliot images, generates a local .env, starts all three
# services, and opens Studio. The only prerequisite is Docker — no Python,
# Node, uv, or pnpm. Re-running is safe: an existing .env is never overwritten.
set -eu

REPO_RAW="https://raw.githubusercontent.com/EliBarak12/Elliot/main"
COMPOSE_FILE="docker-compose.run.yml"
INSTALL_DIR="${ELLIOT_HOME:-elliot}"
STUDIO_URL="http://localhost:8080"

say() { printf '%s\n' "$*"; }
err() { printf 'Error: %s\n' "$*" >&2; }

# Generate $1 random bytes as lowercase hex.
gen_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  elif [ -r /dev/urandom ]; then
    od -An -tx1 -N "$1" /dev/urandom | tr -d ' \n'
  else
    err "No openssl and no /dev/urandom available — cannot generate a secret key."
    exit 1
  fi
}

# 1. Preconditions ----------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  err "Docker is not installed. Get it at https://docs.docker.com/get-docker/"
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose v2 is required. Update Docker Desktop or install the compose plugin."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  err "Docker is installed but not running. Start Docker and re-run this installer."
  exit 1
fi

# 2. Workspace --------------------------------------------------------------
mkdir -p "$INSTALL_DIR/connectors"
cd "$INSTALL_DIR"

# 3. Compose file -----------------------------------------------------------
say "Downloading $COMPOSE_FILE ..."
curl -LsSf "$REPO_RAW/$COMPOSE_FILE" -o "$COMPOSE_FILE"

# 3b. Demo connector ---------------------------------------------------------
# A fresh install should open on working tools, not an empty dashboard: the
# runtime preloads this connector when no other is configured (opt out with
# ELLIOT_PRELOAD_DEMO=false in .env). Best-effort — Elliot runs without it.
if [ ! -f connectors/my-saas.connector.json ]; then
  say "Downloading the demo connector ..."
  mkdir -p connectors/data
  if curl -LsSf "$REPO_RAW/connectors/my-saas.connector.json" -o connectors/my-saas.connector.json \
     && curl -LsSf "$REPO_RAW/connectors/data/customers.json" -o connectors/data/customers.json \
     && curl -LsSf "$REPO_RAW/connectors/data/events.json" -o connectors/data/events.json; then
    curl -LsSf "$REPO_RAW/connectors/my-saas.eval.yaml" -o connectors/my-saas.eval.yaml || true
  else
    err "Demo connector download failed — continuing without it."
    rm -f connectors/my-saas.connector.json connectors/data/customers.json connectors/data/events.json
  fi
fi

# 4. .env with a generated secret key (never overwrite an existing one) -----
if [ -f .env ]; then
  say "Keeping existing .env"
else
  say "Generating .env with a fresh secret key ..."
  cat > .env <<EOF
# Generated by the Elliot installer on $(date -u +%Y-%m-%dT%H:%M:%SZ).
#
# This is a loopback-only deployment: every service binds to 127.0.0.1, so
# API-key auth is left off. To expose Elliot beyond this machine, set
# ELLIOT_ENV=production and a strong ELLIOT_API_KEY (and VITE_API_KEY to match).
ELLIOT_ENV=development
ELLIOT_SECRET_KEY=$(gen_hex 32)
ELLIOT_STUDIO_ORIGIN=$STUDIO_URL
LOG_LEVEL=INFO
EOF
fi

# 5. Pull + start -----------------------------------------------------------
say "Pulling Elliot images ..."
if ! docker compose -f "$COMPOSE_FILE" pull; then
  err ""
  err "Could not pull the Elliot images from ghcr.io (access denied)."
  err ""
  err "The most common cause is that the published packages are still"
  err "private. GHCR packages are created private by default — even when"
  err "the source repository is public — so an anonymous pull is denied."
  err ""
  err "Maintainer fix (one-time): make each package public at"
  err "  https://github.com/users/EliBarak12/packages"
  err "  -> elliot-plugin / elliot-runtime / elliot-studio"
  err "  -> Package settings -> Danger Zone -> Change visibility -> Public"
  err ""
  err "Alternatively, authenticate with a GitHub token that has the"
  err "'read:packages' scope, then re-run this installer:"
  err "  echo \"\$GITHUB_TOKEN\" | docker login ghcr.io -u <github-username> --password-stdin"
  exit 1
fi
say "Starting Elliot ..."
docker compose -f "$COMPOSE_FILE" up -d

# 6. Wait for Studio to become healthy --------------------------------------
say "Waiting for Studio to come up ..."
i=0
until curl -fsS "$STUDIO_URL/healthz" >/dev/null 2>&1; do
  i=$((i + 1))
  if [ "$i" -gt 60 ]; then
    err "Studio did not become healthy in time."
    err "Check logs: cd $INSTALL_DIR && docker compose -f $COMPOSE_FILE logs"
    exit 1
  fi
  sleep 2
done

# 7. Done -------------------------------------------------------------------
say ""
say "Elliot is running."
say "  Studio:   $STUDIO_URL"
say "  Plugin:   http://localhost:3000   (MCP endpoint: http://localhost:3000/mcp/)"
say "  Runtime:  http://localhost:3001"
say ""
say "  Stop:     cd $INSTALL_DIR && docker compose -f $COMPOSE_FILE down"
say "  Logs:     cd $INSTALL_DIR && docker compose -f $COMPOSE_FILE logs -f"
say "  Update:   cd $INSTALL_DIR && docker compose -f $COMPOSE_FILE pull && docker compose -f $COMPOSE_FILE up -d"
say ""

if command -v open >/dev/null 2>&1; then
  open "$STUDIO_URL" >/dev/null 2>&1 || true
elif command -v xdg-open >/dev/null 2>&1; then
  xdg-open "$STUDIO_URL" >/dev/null 2>&1 || true
fi
