"""Export a connector as an installable Codex + Claude Code plugin.

A user builds a connector with Elliot and ends up with a single
`*.connector.json` file. `export_plugin` wraps that connector in a plugin
scaffold so it can be installed natively in Codex *and* Claude Code — not
just registered as a loose MCP server.

The generated plugin serves the connector over stdio with
`elliot-mcp --connector <path>`, so it works the same way in every host that
speaks MCP. Layout (everything resolved relative to the plugin root):

    <out>/
      .claude-plugin/plugin.json        Claude Code manifest
      .claude-plugin/marketplace.json   Claude Code marketplace catalog
      .codex-plugin/plugin.json         Codex manifest
      .agents/plugins/marketplace.json  Codex marketplace catalog
      .mcp.json                         MCP server (auto-discovered by Claude Code)
      <slug>.connector.json             the connector itself
      README.md                         install instructions
"""

from __future__ import annotations

import json
from pathlib import Path

import structlog

from elliot_core.connector.serializer import deserialize_connector
from elliot_core.types import ConnectorConfig

log = structlog.get_logger(__name__)

# Codex sets CLAUDE_PLUGIN_ROOT alongside PLUGIN_ROOT for compatibility, and
# Claude Code expands it natively in .mcp.json — so a single placeholder works
# for both hosts.
_PLUGIN_ROOT_VAR = "${CLAUDE_PLUGIN_ROOT}"


def _mcp_server(slug: str, connector_filename: str) -> dict[str, object]:
    """The stdio MCP server entry shared by both manifests."""
    return {
        "command": "elliot-mcp",
        "args": ["--connector", f"{_PLUGIN_ROOT_VAR}/{connector_filename}"],
    }


def _claude_plugin_manifest(config: ConnectorConfig) -> dict[str, object]:
    return {
        "name": config.slug,
        "version": config.version,
        "description": config.description or f"Agent-ready tools for {config.name}.",
        "keywords": ["mcp", "connector", "elliot", config.slug],
        "mcpServers": "./.mcp.json",
    }


def _claude_marketplace(config: ConnectorConfig) -> dict[str, object]:
    return {
        "name": config.slug,
        "owner": {"name": "Elliot connector"},
        "description": f"Elliot connector plugin for {config.name}.",
        "version": config.version,
        "plugins": [
            {
                "name": config.slug,
                "source": "./",
                "description": config.description or f"Agent-ready tools for {config.name}.",
                "version": config.version,
            }
        ],
    }


def _codex_plugin_manifest(config: ConnectorConfig, connector_filename: str) -> dict[str, object]:
    short = config.description or f"Agent-ready tools for {config.name}."
    return {
        "name": config.slug,
        "version": config.version,
        "description": short,
        "keywords": ["mcp", "connector", "elliot", config.slug],
        "mcpServers": {config.slug: _mcp_server(config.slug, connector_filename)},
        "interface": {
            "displayName": config.name,
            "shortDescription": short[:100],
            "longDescription": short,
            "category": "Productivity",
            "capabilities": ["Read", "Write"],
        },
    }


def _codex_marketplace(config: ConnectorConfig) -> dict[str, object]:
    return {
        "name": config.slug,
        "interface": {"displayName": config.name},
        "plugins": [
            {
                "name": config.slug,
                "source": {"source": "local", "path": "./"},
                "description": config.description or f"Agent-ready tools for {config.name}.",
                "version": config.version,
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": "Productivity",
            }
        ],
    }


def _readme(config: ConnectorConfig, connector_filename: str) -> str:
    tool_count = len(config.tools)
    return f"""# {config.name} — Elliot connector plugin

This plugin exposes the **{config.name}** connector ({tool_count} tool(s)) as an
MCP server you can install in Codex or Claude Code. It was generated by
`elliot export-plugin`.

## Prerequisite

The plugin runs the connector with the `elliot-mcp` command, so that command
must be on your `PATH`:

```
uv tool install elliot-mcp-plugin
# or: pipx install elliot-mcp-plugin
```

If the connector needs secrets, export them before launching your agent — the
connector file references them as `{{{{ env:VAR }}}}` and Elliot reads them from
`ELLIOT_SECRET_*` environment variables.

## Install in Claude Code

```
/plugin marketplace add /absolute/path/to/this/folder
/plugin install {config.slug}@{config.slug}
```

## Install in Codex

```
codex plugin marketplace add /absolute/path/to/this/folder
```

Then open the plugin directory in Codex and install **{config.slug}**.

## What's inside

- `{connector_filename}` — the connector definition
- `.mcp.json` — runs `elliot-mcp --connector {connector_filename}`
- `.claude-plugin/` — Claude Code manifest + marketplace
- `.codex-plugin/` — Codex manifest
- `.agents/plugins/marketplace.json` — Codex marketplace
"""


def _write_json(path: Path, data: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def export_plugin(connector_path: str | Path, out_dir: str | Path) -> list[Path]:
    """Scaffold an installable Codex + Claude Code plugin from a connector file.

    Returns the list of files written. Raises FileNotFoundError if the
    connector file is missing and ElliotError if it fails to deserialize.
    """
    connector_path = Path(connector_path)
    if not connector_path.exists():
        raise FileNotFoundError(f"connector file not found: {connector_path}")

    raw = connector_path.read_text(encoding="utf-8")
    config = deserialize_connector(raw)

    out = Path(out_dir)
    connector_filename = f"{config.slug}.connector.json"

    written: list[Path] = []

    connector_dst = out / connector_filename
    connector_dst.parent.mkdir(parents=True, exist_ok=True)
    connector_dst.write_text(raw, encoding="utf-8")
    written.append(connector_dst)

    targets: list[tuple[Path, dict[str, object]]] = [
        (
            out / ".mcp.json",
            {"mcpServers": {config.slug: _mcp_server(config.slug, connector_filename)}},
        ),
        (out / ".claude-plugin" / "plugin.json", _claude_plugin_manifest(config)),
        (out / ".claude-plugin" / "marketplace.json", _claude_marketplace(config)),
        (
            out / ".codex-plugin" / "plugin.json",
            _codex_plugin_manifest(config, connector_filename),
        ),
        (out / ".agents" / "plugins" / "marketplace.json", _codex_marketplace(config)),
    ]
    for path, data in targets:
        _write_json(path, data)
        written.append(path)

    readme = out / "README.md"
    readme.write_text(_readme(config, connector_filename), encoding="utf-8")
    written.append(readme)

    log.info(
        "plugin_export.done",
        connector=config.slug,
        out_dir=str(out),
        files=len(written),
    )
    return written
